export const FILTER_CONFIG = [
  {
    key: "department",
    label: "학부 선택",
    type: "select",
    fetch: true,
    placeholder: "학부 선택",
  },
  {
    key: "tradeType",
    label: "거래유형",
    type: "button",
    options: ["전체", "월세", "전세"],
    default: "전체",
  },
  {
    key: "depositRange",
    label: "보증금 (만원)",
    type: "slider",
    min: 0,
    max: 10000,
    step: 10,
    default: [0, 1000],
  },
  {
    key: "priceRange",
    label: "월세/전세가 (만원)",
    type: "slider",
    min: 0,
    max: 1000,
    step: 1,
    default: [0, 100],
  },
  {
    key: "roomType",
    label: "방 종류",
    type: "button",
    options: ["전체", "원룸", "1.5룸", "투룸 이상"],
    default: "전체",
  },
  {
    key: "distanceType",
    label: "학교까지 거리/시간",
    type: "button",
    options: ["도보 10분 내", "자전거 15분 내", "셔틀 정류장 인근"],
    default: "",
  },
  {
    key: "facilities",
    label: "주변 시설",
    type: "checkbox",
    options: ["스터디 카페", "코인세탁소", "24시 마트", "헬스장"],
    default: [],
  },
  {
    key: "safety",
    label: "안전 옵션",
    type: "checkbox",
    options: ["여성 전용", "24시 경비/CCTV", "대로변 위치"],
    default: [],
  },
  {
    key: "living",
    label: "주거 환경",
    type: "checkbox",
    options: ["벌레 없는 집", "방음 우수", "남향/채광"],
    default: [],
  },
  {
    key: "petAllowed",
    label: "반려동물",
    type: "switch",
    default: false,
  },
  {
    key: "contractPeriod",
    label: "계약 기간",
    type: "button",
    options: ["1년 이하 단기", "2년"],
    default: "",
  },
  {
    key: "maintenanceIncl",
    label: "관리비 포함 항목",
    type: "checkbox",
    options: ["인터넷", "수도세", "가스비", "TV"],
    default: [],
  },
  {
    key: "loanType",
    label: "전세 대출",
    type: "button",
    options: ["가능", "버팀목 가능", "중기청 가능"],
    default: "",
  },
  {
    key: "roomOptions",
    label: "방 옵션",
    type: "checkbox",
    options: ["침대", "책상/의자", "전자레인지", "에어컨"],
    default: [],
  },
  {
    key: "roomSize",
    label: "방 크기(㎡)",
    type: "number",
    default: "",
    placeholder: "예: 15",
  },
  {
    key: "floor",
    label: "층수",
    type: "number",
    default: "",
    placeholder: "예: 2",
  },
];
